### ISSUE TITLE
Dose simulation is wrong

### ISSUE THREAD

**Issue by JJPPeters** [ADyson/clTEM#78]
Dose simulation seems ~1000 times less than the input value.

Experimental image 40000 e/A^2
![untitled2](https://cloud.githubusercontent.com/assets/7272521/3656129/f17664aa-1182-11e4-8f82-327982de28f6.png)

CUDA simulation
![untitled3](https://cloud.githubusercontent.com/assets/7272521/3656135/051bca2c-1183-11e4-9860-1f50886da726.png)

clTEM - 40000000 e/A^2
![untitled](https://cloud.githubusercontent.com/assets/7272521/3656139/0ed3fe86-1183-11e4-8d9b-c7b98ef48833.png)

**Comment by ADyson** [comment]
![image](https://cloud.githubusercontent.com/assets/4589471/3656947/0f4939c0-118e-11e4-83c7-a5bf65e7efb7.png)

This is what i get for 40000 e/A^2 , 2048 image. Looks pretty close to me :)

**Comment by JJPPeters** [comment]
On further inspection error seems to be in choice of parameters. Perhaps a change in defaults to be a bit more 'realistic' is needed.
